module.exports = {
  macncheese: {
    name: 'Mac N Cheese',
    image: 'https://s3-us-west-2.amazonaws.com/philinthekitchen/mac-n-chese.jpg',
    desc: 'A very quick and spicy Vegan Mac N Cheese for the lazy cook',
    likes: 0,
    commentCount: 0,
    comments: [],
    tags: ['spicy', 'pasta', 'cheese', 'potato', 'sweet potato'],
    recipe: {
      ingredients: ['1 box whole wheat shells', '1 potato', '1 sweet potato', '3T nutritional yeast', '1t turmeric', '1t each garlic and onion powder', '2T korean red pepper flakes', '1/2t white pepper'],
      method: ''
    },
    recipeVideo: '',
  },
  sloppyjoes: {
    name: 'Sloppy Joes',
    image: 'https://s3-us-west-2.amazonaws.com/philinthekitchen/sloppy-joes.jpg',
    desc: 'Sloppy Joes, you know, if Joe were a Vegan',
    likes: 0,
    commentCount: 0,
    comments: [],
    tags: ['sweet potato', 'carrot', 'sandwich'],
    recipe: '',
    recipeVideo: '',
  },
  berberechickpeas: {
    name: 'Berebere Roasted Chickpeas',
    image: 'https://s3-us-west-2.amazonaws.com/philinthekitchen/berbere-chickpeas.jpg',
    desc: 'Roasted chickpeas with a bit of Ethiopian flair',
    likes: 0,
    commentCount: 0,
    comments: [],
    tags: ['ethiopian', 'chickpea', 'air fryer'],
    recipe: '',
    recipeVideo: '',
  },
  flatbread: {
    name: 'Sweet Potato Flatbread',
    image: 'https://s3-us-west-2.amazonaws.com/philinthekitchen/flatbread.jpg',
    desc: 'A simple no frills way to carb your meals up',
    likes: 0,
    commentCount: 0,
    comments: [],
    tags: ['sweet potato', 'bread', 'flour'],
    recipe: '',
    recipeVideo: '',
  },
  biangbiang: {
    name: 'Biang Biang Noodles',
    image: 'https://s3-us-west-2.amazonaws.com/philinthekitchen/biang-biang.jpg',
    desc: 'Shaanxi style spicy noodles with blanched bokchoy',
    likes: 0,
    commentCount: 0,
    comments: [],
    tags: ['flour', 'noodles', 'bok choy', 'chinese'],
    recipe: '',
    recipeVideo: '',
  },
  pizza: {
    name: 'Homemade Pizza',
    image: 'https://s3-us-west-2.amazonaws.com/philinthekitchen/pizza.jpg',
    desc: 'This recipes has a lot of steps but is worth the effort',
    likes: 0,
    commentCount: 0,
    comments: [],
    tags: ['pizza', 'flour', 'cheese', 'mushrooms'],
    recipe: '',
    recipeVideo: '',
  },
  mesiratakilt: {
    name: 'Mesir & Atakilt Wat',
    image: 'https://s3-us-west-2.amazonaws.com/philinthekitchen/mesir-atakilt-wat.jpg',
    desc: 'Ethiopian red lentil stew and spiced cabbage, potato, and carrots',
    likes: 0,
    commentCount: 0,
    comments: [],
    tags: ['spicy', 'ethiopian', 'lentils', 'potato', 'carrot', 'cabbage', 'stews'],
    recipe: '',
    recipeVideo: '',
  }
}
