module.exports = {
  macncheese: {
    name: 'Mac N Cheese',
    image: 'https://s3-us-west-2.amazonaws.com/philinthekitchen/mac-n-chese.jpg',
    desc: 'A very quick and spicy Vegan Mac N Cheese for the lazy cook',
    likes: 0,
    commentCount: 0,
    comments: [],
    tags: ['spicy', 'pasta', 'cheese', 'potato', 'sweet potato'],
    recipe: {
      ingredients: ['1 box whole wheat shells', '1 potato, peeled and cubed', '1 sweet potato, peeled and cubed', '3T nutritional yeast', '1t turmeric', '2T tahini','1t each garlic and onion powder', '2T korean red pepper flakes', '1/2t white pepper'],
      method: 'Start by boiling the potato and sweet potato until soft. Cook the pasta according to package instructions and drain, but do not rinse. In a powerful blender, add the boiled potato and sweet potato, a cup of the starchy water used to cook the potatoes, and all of the seasoning. Blend until smooth. Pour over cooked pasta and mix until well coated.',
      notes: 'Garnish with smoked paprika. You can replace the potato or sweet potato with carrots or squash if preferred. To adjust cheese sauce: add mustard for tang, soy sauce for saltiness, or cashews/more tahini for more fat and body.'
    },
    recipeVideo: '',
  },
  sloppyjoes: {
    name: 'Sloppy Joes',
    image: 'https://s3-us-west-2.amazonaws.com/philinthekitchen/sloppy-joes.jpg',
    desc: 'Sloppy Joes, you know, if Joe were a Vegan',
    likes: 0,
    commentCount: 0,
    comments: [],
    tags: ['sweet potato', 'carrot', 'sandwich'],
    recipe: '',
    recipeVideo: '',
  },
  berberechickpeas: {
    name: 'Berebere Roasted Chickpeas',
    image: 'https://s3-us-west-2.amazonaws.com/philinthekitchen/berbere-chickpeas.jpg',
    desc: 'Roasted chickpeas with a bit of Ethiopian flair',
    likes: 0,
    commentCount: 0,
    comments: [],
    tags: ['ethiopian', 'chickpeas', 'air fryer'],
    recipe: '',
    recipeVideo: '',
  },
  flatbread: {
    name: 'Sweet Potato Flatbread',
    image: 'https://s3-us-west-2.amazonaws.com/philinthekitchen/flatbread.jpg',
    desc: 'A simple no frills way to carb your meals up',
    likes: 0,
    commentCount: 0,
    comments: [],
    tags: ['sweet potato', 'bread', 'flour'],
    recipe: '',
    recipeVideo: '',
  },
  biangbiang: {
    name: 'Biang Biang Noodles',
    image: 'https://s3-us-west-2.amazonaws.com/philinthekitchen/biang-biang.jpg',
    desc: 'Shaanxi style spicy noodles with blanched bokchoy',
    likes: 0,
    commentCount: 0,
    comments: [],
    tags: ['flour', 'noodles', 'bok choy', 'chinese'],
    recipe: '',
    recipeVideo: '',
  },
  pizza: {
    name: 'Homemade Pizza',
    image: 'https://s3-us-west-2.amazonaws.com/philinthekitchen/pizza.jpg',
    desc: 'This recipes has a lot of steps but is worth the effort',
    likes: 0,
    commentCount: 0,
    comments: [],
    tags: ['pizza', 'flour', 'cheese', 'mushrooms'],
    recipe: '',
    recipeVideo: '',
  },
  mesiratakilt: {
    name: 'Mesir & Atakilt Wat',
    image: 'https://s3-us-west-2.amazonaws.com/philinthekitchen/mesir-atakilt-wat.jpg',
    desc: 'Ethiopian red lentil stew and spiced cabbage, potato, and carrots',
    likes: 0,
    commentCount: 0,
    comments: [],
    tags: ['spicy', 'ethiopian', 'lentils', 'potato', 'carrot', 'cabbage', 'stews'],
    recipe: '',
    recipeVideo: '',
  },
  crabcakes: {
    name: 'Crab Cakes',
    image: 'https://s3-us-west-2.amazonaws.com/philinthekitchen/crab-cakes.jpg',
    desc: 'Mayo-free Vegan Crab Cakes with Sriracha Cream Sauce',
    likes: 0,
    commentCount: 0,
    comments: [],
    tags: ['spicy', 'seafood', 'chickpeas', 'artichoke hearts', 'hearts of palm'],
    recipe: '',
    recipeVideo: '',
  },
  burger: {
    name: 'Black Bean, Sweet Potato, Seitan Burger',
    image: 'https://s3-us-west-2.amazonaws.com/philinthekitchen/burger.jpg',
    desc: 'My newest burger recipe',
    likes: 0,
    commentCount: 0,
    comments: [],
    tags: ['black beans', 'sweet potato', 'seitan', 'sandwich'],
    recipe: '',
    recipeVideo: '',
  }
}
