module.exports = {
  macncheese: {
    name: 'Mac N Cheese',
    image: 'https://s3-us-west-2.amazonaws.com/philinthekitchen/mac-n-chese.jpg',
    desc: 'A very quick and spicy Vegan Mac N Cheese for the lazy cook',
    likes: 0,
    commentCount: 0,
    comments: [],
    tags: ['spicy', 'pasta', 'cheese'],
    recipe: '',
    recipeVideo: '',
  },
  sloppyjoes: {
    name: 'Sloppy Joes',
    image: 'https://s3-us-west-2.amazonaws.com/philinthekitchen/sloppy-joes.jpg',
    desc: 'Sloppy Joes, you know, if Joe were a Vegan',
    likes: 0,
    commentCount: 0,
    comments: [],
    tags: ['sweet potato', 'carrot', 'sandwich'],
    recipe: '',
    recipeVideo: '',
  },
  berberechickpeas: {
    name: 'Berebere Roasted Chickpeas',
    image: 'https://s3-us-west-2.amazonaws.com/philinthekitchen/berbere-chickpeas.jpg',
    desc: 'Roasted chickpeas with a bit of Ethiopian flair',
    likes: 0,
    commentCount: 0,
    comments: [],
    tags: ['ethiopian', 'chickpea', 'air fryer'],
    recipe: '',
    recipeVideo: '',
  },
  macncheese1: {
    name: 'Mac N Cheese',
    image: 'https://s3-us-west-2.amazonaws.com/philinthekitchen/mac-n-chese.jpg',
    desc: 'A very quick and spicy Vegan Mac N Cheese for the lazy cook',
    likes: 0,
    commentCount: 0,
    comments: [],
    tags: ['spicy', 'pasta', 'cheese'],
    recipe: '',
    recipeVideo: '',
  },
  sloppyjoes1: {
    name: 'Sloppy Joes',
    image: 'https://s3-us-west-2.amazonaws.com/philinthekitchen/sloppy-joes.jpg',
    desc: 'Sloppy Joes, you know, if Joe were a Vegan',
    likes: 0,
    commentCount: 0,
    comments: [],
    tags: ['sweet potato', 'carrot', 'sandwich'],
    recipe: '',
    recipeVideo: '',
  },
  berberechickpeas1: {
    name: 'Berebere Roasted Chickpeas',
    image: 'https://s3-us-west-2.amazonaws.com/philinthekitchen/berbere-chickpeas.jpg',
    desc: 'Roasted chickpeas with a bit of Ethiopian flair',
    likes: 0,
    commentCount: 0,
    comments: [],
    tags: ['ethiopian', 'chickpea', 'air fryer'],
    recipe: '',
    recipeVideo: '',
  },
}
